# Generated by Django 4.0 on 2021-12-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='model_name',
            new_name='model',
        ),
    ]
